using BlazorMedCalculator.Web.Interfaces;
using BlazorMedCalculator.Web.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BlazorMedCalculator.Web.Infrastructure.Pdf;

public sealed class QuestPdfExportService : IPdfExportService
{
    static QuestPdfExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    private static readonly Dictionary<string, string> Labels = new()
    {
        // Inputs
        ["weightKg"] = "Weight (kg)",
        ["heightCm"] = "Height (cm)",

        // Outputs
        ["bmi"] = "Body Mass Index (BMI)",
        ["category"] = "Classification"
    };

    public byte[] Generate(CalculationResult result)
    {
        var document = new CalculationResultDocument(result);
        return document.GeneratePdf();
    }

    private sealed class CalculationResultDocument : IDocument
    {
        private readonly CalculationResult _result;

        public CalculationResultDocument(CalculationResult result)
        {
            _result = result;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text("Medical Calculator Result")
                    .FontSize(20)
                    .Bold()
                    .AlignCenter();

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(10);

                    column.Item().Text($"Calculator: {_result.CalculatorCode.ToUpper()}")
                        .FontSize(14)
                        .Bold();

                    column.Item().LineHorizontal(1);

                    column.Item().Text("Parameters").Bold();

                    foreach (var input in _result.Inputs)
                    {
                        var label = Labels.GetValueOrDefault(input.Key, input.Key);
                        column.Item().Text($"{label}: {input.Value}");
                    }

                    column.Item().LineHorizontal(1);

                    column.Item().Text("Results").Bold();

                    foreach (var output in _result.Outputs)
                    {
                        var label = Labels.GetValueOrDefault(output.Key, output.Key);
                        column.Item().Text($"{label}: {output.Value}");
                    }
                });

                page.Footer()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated by BlazorMedCalculator");
                    });
            });
        }
    }
}
